options:
  logging: CLOUD_LOGGING_ONLY 
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/testing-dep-471617/etl-service', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/testing-dep-471617/etl-service']

timeout: 1200s
