options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'COMPOSER_NAME=etl-composer' 
    - 'COMPOSER_LOCATION=asia-south1'

steps:
  # Sync DAGs to Composer bucket
  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      #!/bin/bash
      echo "Syncing DAGs to Composer..."
      DAG_BUCKET=$(gcloud composer environments describe $COMPOSER_NAME \
        --location $COMPOSER_LOCATION \
        --format='value(config.dagGcsPrefix)')
      
      echo "Target bucket: $DAG_BUCKET"
      gcloud storage rsync -r -J --delete-unmatched-destination-objects \
        dags/ $DAG_BUCKET
      
      echo "✅ DAGs synced successfully!"

timeout: 600s
